name: Upload_Transfer

on:
  watch:
    types: [started]
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == Pinkdoge

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install wget curl

       - name: Get variables
         run: |
          echo "::set-output name=rom_url::$(jq -r '.rom_url' config.json)"
          echo "::set-output name=rom_from::$(jq -r '.rom_from' config.json)"
          echo "::set-output name=and_ver::$(jq -r '.and_ver' config.json)"
          echo "::set-output name=rom_ver::$(jq -r '.rom_ver' config.json)"
          echo "::set-output name=rom_origin::$(jq -r '.rom_origin' config.json)"
          echo "::set-output name=device_name::$(jq -r '.device_name' config.json)"
          echo "::set-output name=rom_author::$(jq -r '.rom_author' config.json)"
         id: var

       - name: Download Rom
         run: wget -c ${{ steps.var.outputs.rom_url }} -O ${{ steps.var.outputs.rom_from }}-${{ steps.var.outputs.and_ver }}_${{ steps.var.outputs.rom_ver }}-${{ steps.var.outputs.rom_origin }}_${{ steps.var.outputs.device_name }}_${{ steps.var.outputs.rom_author }}.zip
       
       - name: Upload Rom To Release
         uses: softprops/action-gh-release@v1
         with:
           files: ${{ steps.var.outputs.rom_from }}-${{ steps.var.outputs.and_ver }}_${{ steps.var.outputs.rom_ver }}-${{ steps.var.outputs.rom_origin }}_${{ steps.var.outputs.device_name }}_${{ steps.var.outputs.rom_author }}.zip
           name: ${{ steps.var.outputs.rom_from }} ${{ steps.var.outputs.rom_ver }} ${{ steps.var.outputs.rom_origin }} ${{ steps.var.outputs.device_name }} by ${{ steps.var.outputs.rom_author }}
           tag_name: ${{ steps.var.outputs.device_name }}
           body: Synchronous upstream source code update
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
#       - name: Upload Rom to WeTransfer
#         run: |
#              curl -sL https://git.io/file-transfer | sh
#             ./transfer wet ${{ steps.var.outputs.rom_from }}-${{ steps.var.outputs.and_ver }}_${{ steps.var.outputs.rom_ver }}-${{ steps.var.outputs.rom_origin }}_${{ steps.var.outputs.device_name }}_${{ steps.var.outputs.rom_author }}.zip

#       - name: Upload Rom to Bitsend
#         run: ./transfer bit ${{ steps.var.outputs.rom_from }}-${{ steps.var.outputs.and_ver }}_${{ steps.var.outputs.rom_ver }}-${{ steps.var.outputs.rom_origin }}_${{ steps.var.outputs.device_name }}_${{ steps.var.outputs.rom_author }}.zip
              
#       - name: Upload Rom to GoFile
#         run: ./transfer gof ${{ steps.var.outputs.rom_from }}-${{ steps.var.outputs.and_ver }}_${{ steps.var.outputs.rom_ver }}-${{ steps.var.outputs.rom_origin }}_${{ steps.var.outputs.device_name }}_${{ steps.var.outputs.rom_author }}.zip

